#!/bin/bash -l

#Author: Mrugakshi Chidrawar

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

## load all modules
module load python3
module load rseqc
module load samtools

geneBody_coverage.py -i P0_1_tophat/accepted_hits.bam -r /project/bf528/project_2/reference/annot/mm9.bed -o geneBody_coverage_output
inner_distance.py -i P0_1_tophat/accepted_hits.bam -r /project/bf528/project_2/reference/annot/mm9.bed -o inner_distance_output
bam_stat.py -i P0_1_tophat/accepted_hits.bam

echo "Job finished: $(date +%F)"
