#!/bin/bash -l

#Author: Mrugakshi Chidrawar

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

#Load modules
module load cufflinks

cufflinks --compatible-hits-norm \
            -G /project/bf528/project_2/reference/annot/mm9.gtf \
            -b /project/bf528/project_2/reference/mm9.fa \
            -u \
            -o P0_1_cufflinks \
            -p 16 \
            /projectnb/bf528/students/mruga77/P0_1_tophat/accepted_hits.bam

echo "Job finished: $(date +%F)"
